name: Release
on:
  push:
    branches:
      - master
      - beta

jobs:
  release:
    if: "(!contains(github.event.head_commit.message, 'skip ci')) || (contains(github.head_ref, 'beta'))"
    name: Release
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 13.14
      - name: Install dependencies
        run: yarn install
      - name: Build Lib
        run: yarn build
      - name: Release
        env:
          NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npx semantic-release
