name: Release
on:
  push:
    branches:
      - main
      - beta

jobs:
  release:
    if: "(!contains(github.event.head_commit.message, 'skip ci')) || (contains(github.head_ref, 'beta'))"
    name: Release
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 13.14
      - name: Install dependencies
        run: yarn install
      - name: Build Lib
        run: yarn build
      - name: Release WEB/NATIVE
        env:
          GH_TOKEN: ${{ secrets.DEPLOY_DEMO }}
          NPM_TOKEN: ${{ secrets.DEPLOY_DEMO }}
        run: |
          npx semantic-release
          echo "//npm.pkg.github.com/:_authToken=$GH_TOKEN" > ~/.npmrc
          cd ../
          cd ./dist-native
          npm publish
